# Generated by Django 3.2.8 on 2022-01-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicalmarketdata',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='historicalmarketdata',
            constraint=models.UniqueConstraint(fields=('stock', 'trading_date'), name='unique_stock_and_trading_date'),
        ),
    ]
